Feature/details
wecode-bootcamp-korea/24-1st-WTP-backend pull request #11
Opened 2021-09-07 08:10 UTC by PeterLEEEEEE

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 사용자 별점 입력 시 디비에 저장 혹은 업데이트
-  영화 장르와 같은 장르의 모든 영화를 가져오는 api 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-07 10:17 UTC, kst6294 reviewed
구두로 설명드린 내용 반영해서 올려주세요!

2021-09-07 10:17 UTC, kst6294 commented on .gitignore
> +
불필요한 공백 제거해주세요!

2021-09-07 10:17 UTC, kst6294 commented on atchapedia/urls.py
> +
공백 제거해주세요!

2021-09-07 10:17 UTC, kst6294 commented on movies/management/commands/data_loader.py
> +class Command(BaseCommand):
구두로 설명드린 내용 반영해주세요~!

2021-09-07 12:34 UTC, PeterLEEEEEE commented on .gitignore
> +
공백 제거하였습니다.

2021-09-07 12:34 UTC, PeterLEEEEEE commented on atchapedia/urls.py
> +
제거 완료했습니다.

2021-09-07 12:43 UTC, PeterLEEEEEE commented on movies/management/commands/data_loader.py
> +class Command(BaseCommand):
리스트 컴프리헨션 사용하였고 class 명도 명사형으로 변경하였습니다.

2021-09-08 07:25 UTC, S2-J1NG requested changes

2021-09-08 07:25 UTC, S2-J1NG commented on movies/views.py
> +                )
별점을 이미 등록했으면 변경된 별점으로 수정하는 거고 없으면 새로 등록하는 로직이죠?
`update_or_created` 쿼리셋 찾아보고 적용해보세요!

2021-09-08 09:46 UTC, merged

2021-09-08 10:32 UTC, S2-J1NG commented
수고하셨습니다 무현님!
`Movie`와 `Genre` 테이블 관계 생각해서 정참조, 역참조, related_name 관계로도 충분히 구현 할 수 있습니다!
리팩토링 할 때 참고해서 진행해보세요₩!