Add:KoreanMovieList_V1
wecode-bootcamp-korea/24-1st-WTP-backend pull request #3
Opened 2021-09-01 17:52 UTC by melody-story

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 한국 영화 목록을 가져오는 메소드 추가.
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- NA

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

1.한국영화를 화면에 띄울때 ,특정한 갯수 만큼만 가져오기위하여 한국영화리스트를 all()로 모두 가져와 
movie_information 리스트에 담았으며, 이를 아래와 같이 postman을 통해 요청받은 개수대로 slice하는 코드를 작성하였으나, 
테스트시 영화 1개만 호출되며, 요청한 5개만큼의 영화리스트가 응답되지 않아, 
리스트를 slice로 잘라내는 접근 방식 자체에 문제가 있는지 여쭙고자 코드리뷰 요청드립니다.
 
'''python
{
    "movies_counts" : 5
}
'''

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-02 01:49 UTC, kst6294 requested changes
수정바랍니다.

2021-09-02 01:49 UTC, kst6294 commented on movies.csv
> +﻿id,title,release_date,genre_id,production_country_id,grade,description,running_time,average_rating,grade_id,poster_image,trailer
csv 는 제외해주세요

2021-09-02 01:49 UTC, kst6294 commented on movies/urls.py
> +#질문 하나의 url안에 여러기능들을 담아야하므로, view들을 하나로 합쳐야하는지?
질문인가요? 이러한 주석은 제거해주세요!

2021-09-02 01:49 UTC, kst6294 commented on movies/urls.py
> +
불필요한 공백은 제거해주세요

2021-09-02 01:49 UTC, kst6294 commented on movies/views.py
> +class GetKoreaMovieList(View):
class 명은 명사로만 이루어지게 해주세요
예: MovieView

2021-09-02 01:49 UTC, kst6294 commented on movies/views.py
> +        data = json.loads(request.body)
get 과 post 의 차이에 대해 한번 확인해보시면 좋겠습니다.

2021-09-02 01:49 UTC, kst6294 commented on movies/views.py
> +        korea_movies       = korea.movie_set.all()
Movie 에서 filter 를 통해 한국 영화를 가져오는 방식으로 해보시겠어요?

2021-09-02 01:49 UTC, kst6294 commented on table_movies.py
> +import csv
uploader는 제외해주세요

2021-09-02 07:16 UTC, lordmyshepherd commented
```
urlpatters = [
    path("movies", MoviewsView.as_view()),
    path("movies/<int:movie_id>", MoviewView.as_view()),
]

GET :8000/movies
GET :8000/movies?filter=netflix

class MyMoviewsView(View):
    @login_required
    def get(self, request):
        print(request)

        movies = Movie.objects.filter(user_id=request.user_id)
        
        return JsonResponse({"movies" : movies}, status=200)


GET :8000/movies/1
class MoviewView(View):
    def get(self, request, movie_id):
        movie = Movie.objects.get(id=movie_id)
        return JsonResponse({"movie" : movie}, status=200)
```

2021-09-02 19:35 UTC, melody-story commented on movies.csv
> +﻿id,title,release_date,genre_id,production_country_id,grade,description,running_time,average_rating,grade_id,poster_image,trailer
수정사항 반영하였습니다.

2021-09-02 19:36 UTC, melody-story commented on movies/urls.py
> +#질문 하나의 url안에 여러기능들을 담아야하므로, view들을 하나로 합쳐야하는지?
수정사항 반영하였습니다.

2021-09-02 19:36 UTC, melody-story commented on movies/urls.py
> +
수정사항 반영하였습니다.

2021-09-02 19:36 UTC, melody-story commented on movies/views.py
> +class GetKoreaMovieList(View):
수정사항 반영하였습니다.

2021-09-02 19:36 UTC, melody-story commented on movies/views.py
> +        data = json.loads(request.body)
확인 후 수정사항 반영하였습니다.

2021-09-02 19:37 UTC, melody-story commented on movies/views.py
> +        korea_movies       = korea.movie_set.all()
DB에 데이터가 저장되지 않았던 것으로 이후 해결되었습니다!

2021-09-02 19:37 UTC, melody-story commented on table_movies.py
> +import csv
수정사항 반영하였습니다.

2021-09-03 01:39 UTC, redsaumon commented on movies.csv
> +악인전,2019-05-23,내용없음,110,3.5,http://atlantachosun.com/files/attach/images/16520/443/189/1a3437e56b00e515d88bcb4500fdb610.jpg,UmebAbuTfXI,5
csv 파일이 아직 올라와있습니다! 다시 한번 확인해주세요.

2021-09-03 01:39 UTC, redsaumon commented on movies/urls.py
> +from movies.views import *
사용할 View만 import 해주세요.

2021-09-03 01:39 UTC, redsaumon commented on movies/views.py
> +from movies.models import *
사용할 객체만 import 해주세요.

2021-09-03 01:39 UTC, redsaumon commented on movies/views.py
> +            offset       = int(request.GET.get("offset",0))
추후 용이한 수정을 위해 limit와 offset은 따로 변수로 빼서 상수화 시켜주세요.

2021-09-03 01:39 UTC, redsaumon commented on movies/views.py
> +                return JsonResponse({"FOREIGN_MOVIES" : movie_list}, status=200)
movie_list를 만드는 부분이 반복되고 있습니다. country_name이 한국일 경우를 기본값으로 movies를 만드신 후 country_name일 경우만 조건문을 만들어 movies를 다시 만들어주시면 동일 코드 반복을 줄일 수 있습니다.
이렇게 바꿔보시고 list_comprehension도 적용해주세요.

2021-09-03 01:39 UTC, redsaumon commented on movies/views.py
> +                return JsonResponse({"MESSAGE" : "KEY_ERROR"}, status=400)
키에러가 발생할 수 있는 기능인지 고민해보시고 지워주세요.

2021-09-03 07:13 UTC, melody-story commented on movies/views.py
> +                return JsonResponse({"MESSAGE" : "KEY_ERROR"}, status=400)
Keyerror는 POST 메소드에서 클라이언트로 전달받은 키:값을 제이슨 형태로 저장시 이때 View의 키값과 일치 하지 않을때 발생하므로  GET메소드에서는 발생하지 않습니다.
수정사항 반영하였습니다.

2021-09-03 07:13 UTC, melody-story commented on movies/views.py
> +            offset       = int(request.GET.get("offset",0))
수정사항 반영하였습니다.

2021-09-03 07:13 UTC, melody-story commented on movies/views.py
> +from movies.models import *
수정사항 반영하였습니다.

2021-09-03 07:13 UTC, melody-story commented on movies/urls.py
> +from movies.views import *
수정사항 반영하였습니다.

2021-09-03 07:13 UTC, melody-story commented on movies.csv
> +악인전,2019-05-23,내용없음,110,3.5,http://atlantachosun.com/files/attach/images/16520/443/189/1a3437e56b00e515d88bcb4500fdb610.jpg,UmebAbuTfXI,5
수정사항 반영하였습니다.

2021-09-03 07:21 UTC, melody-story commented on movies/views.py
> +                return JsonResponse({"FOREIGN_MOVIES" : movie_list}, status=200)
수정사항 반영하였으며, 다만 아래 코드를 통해 나라이름을 가져오려고할 때,  null값으로 가져와져서 코드 리뷰 부탁드립니다..!
```
 for i in range(offset, limit):
            movie_list.append({
                "country_name"   : movies[i].country.name, 
```

2021-09-04 15:41 UTC, melody-story commented
리뷰해주신 내용 반영 및 추가기능 구현하였으며, 의도한 결과가 나오는 것 까지 확인 후 PR요청드립니다.

2021-09-06 01:26 UTC, kst6294 reviewed
확인바랍니다.

2021-09-06 01:26 UTC, kst6294 commented on movies/views.py
> +            return JsonResponse({"MESSAGE" : "PARAMETER_DOSE_NOT_EXIST"}, status=400)
파라미터가 꼭 필요한가요?

보통 RESTful 하게 작성할 경우
GET 0.0.0.0:8000/movie 요청을 보낼 경우, 전체 movie 리스트를 응답받을 것을 기대하게 됩니다.

현재 위와 같이 요청을 할 경우, 기대와는 다르게 parameter_dose_not_exist 가 반환되네요.

의도하신 바가 맞으신가요?

2021-09-06 01:26 UTC, kst6294 commented on movies/views.py
> +        if country_name == "외국":
추가적으로, 위와 같은 경우, genre1 과 genre2에 해당하는 인자값을 모두 받은 경우 어떻게 처리가 되나요?
예
```
0.0.0.0:8000/movie?genre1=asdf&genre2=adkjslfa
```

2021-09-06 01:52 UTC, melody-story commented on movies/views.py
> +        if country_name == "외국":
장르 1과 2 모두에 해당하는 영화 리스트가 호출됩니다.

2021-09-06 01:58 UTC, melody-story commented on movies/views.py
> +            return JsonResponse({"MESSAGE" : "PARAMETER_DOSE_NOT_EXIST"}, status=400)
위 사항은 고려하지 못하였습니다. RESTful 한 uri 고려하여 0.0.0.0:8000/movie 로 요청할 시 전체 영화 리스트 반환하도록 수정하였습니다.!

2021-09-06 03:04 UTC, kst6294 reviewed
우선 파라미터를 받아서 movie 를 호출하기 전에, 
파라미터 없이 전체 movie 를 호출하는 코드먼저 작성해주세요.

2021-09-06 03:04 UTC, kst6294 commented on movies/views.py
> +        if genre1 and genre2:
이경우에 genre1 만 들어오는 경우는 어떻게 되나요?

2021-09-06 06:26 UTC, melody-story commented on movies/views.py
> +        if genre1 and genre2:
둘중 하나만 값이 들어와도 필터되도록 바꾸었습니다!

2021-09-06 10:58 UTC, melody-story commented
순태님 코드리뷰 요청드립니다~!!

2021-09-07 01:11 UTC, kst6294 commented
불필요한 파일 제외하고 다시 올려주세요

2021-09-07 01:52 UTC, melody-story commented
불필요파일 제외 후 재 PR요청드립니다.

2021-09-07 02:10 UTC, kst6294 approved these changes

2021-09-07 02:11 UTC, merged