add: login v1
wecode-bootcamp-korea/24-1st-WTP-backend pull request #4
Opened 2021-09-02 01:21 UTC by PeterLEEEEEE

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 api 구현
- 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-09-02 01:43 UTC, kst6294 requested changes
수정바랍니다.

2021-09-02 01:43 UTC, kst6294 commented on users/views.py
> +            token = jwt.encode({"id": current_user.id}, SECRET_KEY, algorithm='HS256')
algorithm 도 my_settings.py 에 추가해서 관리하는건 어떤가요?

2021-09-02 01:43 UTC, kst6294 commented on users/views.py
> +        except KeyError:
post 메소드 사용시 KeyError 외에 발생할 수 있는 대표적인 에러가 무엇이 있나요?

2021-09-02 01:43 UTC, kst6294 commented on users/urls.py
> +from users.views import Login
공백으로 구분해주세요~!

2021-09-02 01:43 UTC, kst6294 commented on atchapedia/urls.py
> +from users.views import Login
공백으로 구분해주세요!

2021-09-02 01:43 UTC, kst6294 commented on users/utils.py
> +from my_settings import SECRET_KEY
- python
- django
- local app 

기준으로 구분해주세요

2021-09-02 01:43 UTC, kst6294 commented on users/utils.py
> +def login_decorator(func):
아직 작업중인 코드는 제외해주세요

2021-09-02 08:42 UTC, PeterLEEEEEE commented
변경사항 
1. 코드 양식 수정
2. 로그인 value error 추가
3. login decorator 추가

리뷰 반영하여 총 3가지 수정하여 PR 드립니다!

2021-09-02 09:08 UTC, kst6294 commented
각 피드백에 대한 답변 달아 주신후 라벨 변경해주세요!

2021-09-02 10:08 UTC, PeterLEEEEEE commented on users/views.py
> +            token = jwt.encode({"id": current_user.id}, SECRET_KEY, algorithm='HS256')
```python
ALGORITHM = 'HS256'
```
my_settings.py에 추가하였습니다

2021-09-02 10:09 UTC, PeterLEEEEEE commented on users/views.py
> +        except KeyError:
```python
except ValueError:
            return JsonResponse({"message": "VALUE ERROR"}, status=400)
```
keyerror 밑에 ValueError를 추가하였습니다.

2021-09-02 10:10 UTC, PeterLEEEEEE commented on users/urls.py
> +from users.views import Login
```python
from django.urls import path

from users.views import Login
```
공백 구분 완료하였습니다.

2021-09-02 10:11 UTC, PeterLEEEEEE commented on atchapedia/urls.py
> +from users.views import Login
```python
from django.urls import path, include

from users.views import Login
```
공백 구분 완료하였습니다.

2021-09-02 10:11 UTC, PeterLEEEEEE commented on users/utils.py
> +from my_settings import SECRET_KEY
import jwt

```python
from django.http import JsonResponse

from .models     import User
from my_settings import SECRET_KEY, ALGORITHM
```
구분하여 나누었습니다.

2021-09-02 10:12 UTC, PeterLEEEEEE commented on users/utils.py
> +def login_decorator(func):
```python
def login_decorator(func):
    def wrapper(self, request, *args, **kwargs):
        try:
            access_token = request.headers.get("Authorization", None)
            user = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
            request.user = User.objects.get(id = user['id'])

        except jwt.exceptions.DecodeError:                                   
            return JsonResponse({'message' : '일치하지 않는 토큰입니다.' }, status=400)

        except User.DoesNotExist:       
            return JsonResponse({'message' : '존재하지 않는 사용자입니다.'}, status=400)

        return func(self, request, *args, **kwargs)

    return wrapper
```
decorator 함수 작성 완료하였습니다.

2021-09-03 01:41 UTC, redsaumon commented on users/utils.py
> +            return JsonResponse({'message' : '존재하지 않는 사용자입니다.'}, status=400)
로직으로 처리해주세요.

2021-09-03 02:15 UTC, PeterLEEEEEE commented on users/utils.py
> +            return JsonResponse({'message' : '존재하지 않는 사용자입니다.'}, status=400)
```python
if not User.objects.get(id = user['id']):
    return JsonResponse({'message' : '존재하지 않는 사용자입니다.'}, status=400)

request.user = User.objects.get(id = user['id'])

```
로 수정하였습니다.

2021-09-06 01:29 UTC, kst6294 reviewed
확인바랍니다.

2021-09-06 01:29 UTC, kst6294 commented on movies/views.py
> +import json
login 과 관련없는 코드는 제외해주세요.

2021-09-06 01:29 UTC, kst6294 commented on users/utils.py
> +
불필요한 공백은 제거해주세요.

2021-09-06 01:29 UTC, kst6294 commented on users/utils.py
> +            if not User.objects.get(id = user['id']):
user['id'] 에 해당하는 값이 User 테이블에 존재하지 않는 경우 어떻게 되려나요?

2021-09-06 01:29 UTC, kst6294 commented on users/views.py
> +        except KeyError:
바디가 없는 상태로 요청을 보내도 에러가 발생될 것 같습니다.

2021-09-06 08:17 UTC, PeterLEEEEEE commented on users/views.py
> +        except KeyError:
ValueError 추가하였습니다.

2021-09-06 08:17 UTC, PeterLEEEEEE commented on users/utils.py
> +            if not User.objects.get(id = user['id']):
valueerror 추가하였습니다

2021-09-07 01:10 UTC, kst6294 reviewed
csv 같은 파일 제외해주세요

2021-09-07 11:28 UTC, closed without merging